[general]
## Project name. This is a required field.
name = "speedtest"

## Project version (in semver). This is a required field.
version = "0.1.0"

[build]
files = ["main.fix"]

[[dependencies]]
name = "ez-scripting"
version = "0.1.0"
git = { url = "https://github.com/tttmmmyyyy/ez_scripting.git" }
